version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: poll
    volumes:
      - .:/code
    ports:
      - "8000:8000"




  # django:
  #   image: django-docker:0.0.1
  #   build: .
  #   ports:
  #     - "8000:8000"